eureka:
  instance:
    hostname: 125.6.39.120
  client:
    service-url:
      defaultZone: http://admin:1234@125.6.39.120:8761/eureka
front:
  url: https://contxt.co.kr
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: https://contxt.co.kr/login/oauth2/code/github
          google:
            redirect-uri: https://contxt.co.kr/login/oauth2/code/google