spring:
  redis:
    host: 133.186.244.96
    password: '*N2vya7H@muDTwdNMR!'
    database: '11'
    port: '6379'
  security:
    oauth2:
      client:
        registration:
          github:
            client-secret: e8b14a3ade7745c65b13c9a36b8e2970cdb263ef
            redirect-uri: http://localhost:8200/login/oauth2/code/github
            client-id: Ov23liJHzRh0nm6cVdNW
            authorization-grant-type: authorization_code
          google:
            redirect-uri: https://contxt.co.kr/login/oauth2/code/google
            client-id: ENC(Q/bpGndqp7nR//xD6t/C4dfFnnQYUDjVNCxz5jrxEmxiMO7Bb5pkcv60v7AS6kGK6hC4FYKbW06fEKVIaqSRd3qVg9sAiou25W72itbDI+ZyGQjRJCUJKg==)
            client-secret: ENC(t0NV6jS9CT+O1vJ8qhEoeRh+ZpBTrawAcz29VFB6Sx3aGnw3vWgVzEpH5Fp53D7j)
            scope: profile, email
  datasource:
    dbcp2:
      max-idle: '2'
      test-on-borrow: 'true'
      max-total: '2'
      validation-query: select 1
      url: jdbc:mysql://133.186.244.96:3306/nhn_academy_35
      initial-size: '2'
      max-wait-millis: '2000'
      min-idle: '2'
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(WpvQvtj44woYcum6Klx43zFl6AgLFuz2CnNpzdthuFw=)
    username: ENC(qmQi9eTKcsooXlSsDPyEbh8Mi/SK6Vw8)
    url: ENC(G7OZPpSx3fp1/0Q/BevBQNmCEJbH5VPgVyKUbFJLQqU2RwIeY6C66GysYHxLOYmJe/3FViKCDo0OzukFgB4wqGS/MpSt/kP78FhYsK6Ngjai9lccOyS7OsJobo6AKUKs5QcxuIh6yZ5IMlJEwpA1tw==)
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    database: MYSQL
    open-in-view: 'false'
  cache:
    type: redis
  application:
    name: user-management
  profiles:
    active: prod
logging:
  level:
    org:
      springframework:
        security: TRACE
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
server:
  port: '8200'
  tomcat:
    connection-timeout: '20000'
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
jasypt:
  encryptor:
    password: TxtPassword
management:
  endpoints:
    web:
      exposure:
        include: beans, conditions, configprops, env, health, httpexchanges, info, loggers, metrics, mappings, threaddump, shutdown
      base-path: /user-management-server/manage
  endpoint:
    health:
      show-details: always
springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    disable-swagger-default-url: 'true'
    display-request-duration: 'true'
    groups-order: desc
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs
  paths-to-match: /api/**
  show-actuator: 'true'